apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: openai-gpt4
  namespace: kagent
spec:
  provider: OpenAI
  model: gpt-4o-mini
  apiKeySecretRef: openai-secret
  apiKeySecretKey: api-key
