
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: distributed-resilience
spec:
  type: NodePort
  selector:
    app: web
    version: blue  # Cambiar a 'green' para failover
  ports:
  - name: http
    port: 80
    targetPort: 8080
